export const roughData = [{
        carpoolId: 1,
        bookingId: 1,
        startTime: "10 am",
        carpoolingState: "Accepting",
        imgSource: "/bg1.png",
        imgAlt: "Deposite",
        address: "08918590581051095105815",
        origin: "Nazimabad",
        destination: "Saddar",
        numOfSlotsAvailable: 5,
        pricePerSlot: 100,
    },

    {
        bookingId: 2,
        carpoolId: 2,
        startTime: "11 pm",
        carpoolingState: "Closed",
        imgSource: "/bg1.png",
        imgAlt: "Deposite",
        address: "08918590581051095105817",
        origin: "shujabad",
        destination: "kattar",
        numOfSlotsAvailable: 5,
        pricePerSlot: 100,
    },
    {
        carpoolId: 3,
        bookingId: 3,
        startTime: "8 pm",
        carpoolingState: "Closed",
        imgSource: "/bg1.png",
        imgAlt: "Deposite",
        address: "08918590581051095105819",
        origin: "saadi town",
        destination: "hyderabad",
        numOfSlotsAvailable: 5,
        pricePerSlot: 100,
    },
    {
        carpoolId: 4,
        bookingId: 4,
        startTime: "5 pm",
        carpoolingState: "Accepting",
        imgSource: "/bg1.png",
        imgAlt: "Deposite",
        address: "08918590581051095105811",
        origin: "uni",
        destination: "home",
        numOfSlotsAvailable: 5,
        pricePerSlot: 100,
    },
];